# Generated by Django 3.2.9 on 2021-11-14 23:38

from django.db import migrations, models
import portal.utils


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='expired_datetime',
            field=models.DateTimeField(default=portal.utils.one_weeks_later),
        ),
    ]
