# Generated by Django 3.2.9 on 2021-12-03 22:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_alter_announcement_expired_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='announcement_created_by', to='portal.user'),
            preserve_default=False,
        ),
    ]
