# Generated by Django 3.2.9 on 2022-02-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
