# Generated by Django 3.2.9 on 2022-02-28 04:50

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_report_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='raw_file',
            field=models.ImageField(blank=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='raw/'),
        ),
    ]
