# Generated by Django 3.2.9 on 2022-04-05 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20220405_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='online',
        ),
    ]
