# Generated by Django 3.2.9 on 2022-04-17 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_post_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='intro',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
