version: '3.8'

services:
  nginx:
    build: ../nginx
    ports:
      - 1337:80
    depends_on:
      - web

  web:
    build: ../
    command: >
      sh ./setup.prod.sh
    volumes:
      - ../:/usr/src/carricksum-portal/
    expose:
      - 8000
    env_file:
      - ./.env.aws
