version: '3.8'

services:
  nginx:
    build: ../nginx
    ports:
      - 1337:80
    depends_on:
      - web

  db:
    build: ../db
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - ./.env.prod.db

  redis:
    image: redis:alpine

  sqs:
    image: roribio16/alpine-sqs
    ports:
      - 9324:9324
      - 9325:9325
    volumes:
      - ../config/elasticmq.conf:/opt/config/elasticmq.conf

  web:
    build: ../
    command: >
      sh ./setup.prod.sh
    volumes:
      - ../:/usr/src/carricksum-portal/
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
      - sqs
      - redis

volumes:
  postgres_data_prod: