# Generated by Django 3.2.9 on 2022-01-04 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='created_datetime',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='updated_datetime',
        ),
    ]
