# Generated by Django 3.2.9 on 2022-02-01 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_auto_20220104_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
