# Generated by Django 3.2.9 on 2022-02-02 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0004_alter_branch_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='desc',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
