# Generated by Django 3.2.9 on 2022-02-02 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0005_auto_20220202_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='desc',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
