# Generated by Django 3.2.9 on 2022-02-03 23:42

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0006_auto_20220202_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='geo',
            field=django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326),
        ),
    ]
