# Generated by Django 3.2.9 on 2022-02-04 03:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('BuildingName', models.CharField(max_length=100)),
                ('StreetName', models.CharField(max_length=100)),
                ('BuildingNoFrom', models.CharField(blank=True, max_length=5, null=True)),
                ('BuildingNoTo', models.CharField(blank=True, max_length=5, null=True)),
                ('District', models.CharField(max_length=100)),
                ('FullAddress', models.CharField(blank=True, max_length=4000, null=True)),
                ('RelatedDocument', models.CharField(blank=True, max_length=200, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
