# Generated by Django 3.2.9 on 2022-02-06 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_auto_20220206_0205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='RelatedDocument',
            new_name='relatedDocument',
        ),
    ]
