# Generated by Django 3.2.9 on 2022-03-07 23:20

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_rename_relateddocument_address_relateddocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='uploadFile',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='address/'),
        ),
    ]
