# Generated by Django 3.2.9 on 2021-12-19 23:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seminars', '0005_seminar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('unique_string', models.CharField(max_length=32)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_attendee', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_created_by', to=settings.AUTH_USER_MODEL)),
                ('seminar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_seminar', to='seminars.seminar')),
            ],
            options={
                'unique_together': {('seminar', 'attendee')},
            },
        ),
    ]
