# Generated by Django 3.2.9 on 2021-12-20 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0006_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='created',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='updated',
        ),
    ]
