# Generated by Django 3.2.9 on 2021-12-26 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0007_auto_20211220_2328'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set(),
        ),
    ]
