# Generated by Django 3.2.9 on 2022-01-01 13:15

from django.conf import settings
import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import seminars.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seminars', '0008_alter_booking_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('seminar', 'attendee')},
        ),
        migrations.AddConstraint(
            model_name='seminar',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status', 'OP')), expressions=((seminars.models.TsTzRange('start_date_time', 'end_date_time', django.contrib.postgres.fields.ranges.RangeBoundary()), '&&'), ('venue', '=')), name='exclude_overlapping_reservations'),
        ),
    ]
